### ISSUE TITLE
Update FAQ page 

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#630] opened 2022-08-03 02:17 UTC
### Overview
The current FAQ page is overcrowded with questions and answers that make it difficult for users to scan. Content Design also requested to add questions to the page. This issue is an extension of https://github.com/hackforla/expunge-assist/issues/598

### Action Items
- [x] Create a desktop wireframe with an updated menu and footer
- [x] Grab copy from "FAQ-text only" frame under the FAQ page on Figma 
- [x] Add "Can law enforcement get a search warrant to access my data on this site?" question and answer between "Why does expungement or reclassification matter to me?" and "How does Prop 47 help me?" question
- [x] Create a mobile FAQ page with an updated mobile menu and footer and white background
- [x] Handoff to Content for approval 
- [x] Present to Dev
- [x] Create issue for Dev and add to frames to Dev handoff page on figma

### Resources 
[Figma page with up to date FAQ Copy](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=4115%3A30674)

**Comment by jamiesiu** [comment] 2022-08-04 01:21
to assign to Snigdha once their GH username is confirmed

**Comment by SamHyler** [comment] 2022-08-04 12:23
Content for existing FAQs is here: https://docs.google.com/document/d/1O3y2oE_5VdEYDcwdjtdrlPq0d-Rcu_igmzPBcbjli-E/edit. 

We will update in Figma going forward as a source of truth when we add the new questions (and eventually when we rewrite the FAQs)

**Comment by jamiesiu** [comment] 2022-08-18 05:28
Not able to add Snigdha to issue or read/write members list for EA atm. Seems to be permissions/public visibility restriction most likely as they are part of HFLA repo / wider org. Will follow up with them

**Closed** 2022-11-15 00:53 UTC
Labels: role: design, priority: high, size: 2pt, p-feature: FAQ Page
