### ISSUE TITLE
Perform diff analysis between EA Design System and other project Design Systems

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#544] opened 2022-04-21 07:08 UTC
### Overview
Perform diff analysis between other project Design Systems to be able to create recommendation for  improvements to EA Design System 

### Details 
Most Design Systems are created to bring standardization and order to a website, providing a cohesive experience for users. At the same time, it provides guidelines for designers (so that they don’t have to guess and research standards), and creates reusable components and styles for developers (so that they don’t have to write brand new code for every new component on every new page). Our Design System for EA (like many others) was created by the cumulative efforts of previous volunteers and could be further refined so that our current / future teammates and users would benefit. 

### Action Items
- [x] Review Design System Guide and related HFLA website / Civic Tech examples (see Resources below)
- [ ] Evaluate gaps and opportunities based on current [EA Design System in Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A2)
- [ ] Document analysis in Figma

### Resources/Instructions
* [HfLA Universal Design System Guide for Designers](https://docs.google.com/document/d/1zUVnInBcAi3HaoLFoHHjhlmWZvspPxYfg16kAm9nVVY/edit?usp=sharing)
* [Hack for LA Website Design System - Template in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7910%3A768)
* [Civic Tech Index Project Design System - In-Depth Figma Example](https://www.figma.com/file/EFoSuj1b9G4aZ7bN8OX8tf/CivicTechIndex---Master-Design-File?node-id=1329%3A11944)

**Comment by jamiesiu** [comment] 2022-04-27 05:01
@ValeriyaMetla and @RenaNicole will be partnering together here with Daisy supporting

**Comment by ValeriyaMetla** [comment] 2022-07-07 22:52
@jamiesiu if the issue is completed, please close it. Now, it's in Closed Issue column but the issue is reflected as open. Also, please check the boxes for the Action Items if those are complete, and attach document or write in a comment how issue was resolved, any outcomes, next steps.

**Closed** 2022-09-16 05:38 UTC
Labels: role: design, priority: medium, feature: figma design system, size: 5pt
