### ISSUE TITLE
Evaluate transitioning Project Board to use new Project type

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1379] opened 2024-05-02 17:17 UTC
### Overview
Our current Project on Github is using the classic Project type. This is a legacy tool from Github and using the new Project type may improve speeds on the Project Board as well as allow for creation of more complex Github Actions to support our processes.

### Action Items
- [ ] Evaluate the Pros and Cons of transitioning from the Classic Project Type to a new Project.

### Resources/Notes
[Github Project Docs](https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/migrating-from-projects-classic)

**Comment by eburdekin** [comment] 2024-06-22 02:47
Noticed this is a duplicate of #1439

**Closed by eburdekin** 2024-06-22 02:47 UTC
Labels: priority: medium, role: product management, feature: GitHub/Project Board maintenance, size: 2pt, issue level I: request, feature: team operations
